# Придумано notexoff и разработано whymakud.
# Данный плагин полностью отключает использование команд
# прописанных ниже, даже в консоли и у OP.

anti-tab: true
cmd-blocker:
 message: '&7[&bMakudNoCommands&7] &fДанная команда заблокирована, пизда тебе нахуй завтра мы тебя найдем и будем бить публично.'
 commands:
 - 'pl'
 - 'op'
 - 'npc'